name: aishwarya_gold
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  provider: ^6.1.5+1
  table_calendar: ^3.2.0
  flutter_screenutil: ^5.9.3
  fl_chart: ^0.66.1   
  printing: ^5.14.2
  pdf: ^3.11.3
  share_plus: ^12.0.0
  image_picker: ^1.2.0
  dropdown_button2: ^2.3.9
  local_auth: ^2.3.0
  pinput: ^5.0.2
  flutter_launcher_icons: ^0.14.4
  video_player: ^2.10.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  razorpay_flutter: ^1.3.7
  url_launcher: ^6.3.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.0.3
  google_maps_flutter: ^2.13.1
  webview_flutter: ^4.13.1
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  jwt_decoder: ^2.0.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  shimmer: ^3.0.0
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.3
  lottie: ^3.1.2
  video_player_avfoundation: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Aishwaryagoldappicon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/animations/
